<?php

/**
 * @file
 * Contains native_campaigns.module.
 */

/**
 * Implements hook_theme().
 */
function native_campaigns_theme() {
  $theme = [];
  $theme['native_campaign'] = [
    'render element' => 'elements',
    'file' => 'native_campaign.page.inc',
    'template' => 'native_campaign',
  ];
  return $theme;
}


/**
 * Implements hook_theme_suggestions_native_campaign_alter().
 */
function native_campaigns_theme_suggestions_native_campaign_alter(array &$suggestions, array $variables, $hook) {
    if (!empty($variables['elements']['#view_mode'])) {
        $suggestions[] = $hook . '__' . $variables['elements']['#view_mode'];
    }
}