<?php

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 *
 * TODO: Remove when field_promote_states is fully implemented.
 */
function burdastyle_base_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields['promote_top_presenter'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Promoted to top presenter'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 15,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['promote_front_presenter'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Promoted to frontpage presenter'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 16,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['promote_channel'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Promoted to channel page'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 17,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['promote_channel_presenter'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Promoted to channel presenter'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 18,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['is_landing_page'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Is landing page'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 18,
      ])
      ->setDisplayConfigurable('form', TRUE);

    $fields['sponsored'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Mark as sponsored'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDefaultValue(FALSE)
      ->setDisplayOptions('form', [
        'type' => 'boolean_checkbox',
        'settings' => [
          'display_label' => TRUE,
        ],
        'weight' => 19,
      ])
      ->setDisplayConfigurable('form', TRUE);
    return $fields;
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * TODO: Check if this could be placed in a form_alter hook for example in burdastyle_article.
 */
function burdastyle_base_page_attachments_alter(array &$attachments) {
  if (\Drupal::request()->attributes->has('_entity_form') && \Drupal::moduleHandler()->moduleExists('focal_point')) {
    $attachments['#attached']['library'][] = 'focal_point/drupal.focal_point';
  }
}
