<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function burdastyle_headless_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'burdastyle_headless_user_login_submit';
}

/**
 * Form submission handler for user_login_form().
 *
 * Redirects the user to the content overview after logging in.
 */
function burdastyle_headless_user_login_submit(&$form, FormStateInterface $form_state) {
  $url = Url::fromRoute('system.admin_content');

  // Check if a destination was set, probably on an exception controller.
  // @see \Drupal\user\Form\UserLoginForm::submitForm()
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}
