<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Implements hook_form_node_article_edit_form_alter().
 */
function burdastyle_article_form_node_article_edit_form_alter(&$form, FormStateInterface $form_state) {
  _burdastyle_article_form_alter_helper($form, $form_state);
}

/**
 * Implements hook_form_node_article_form_alter().
 */
function burdastyle_article_form_node_article_form_alter(&$form, FormStateInterface $form_state) {
  _burdastyle_article_form_alter_helper($form, $form_state);
}

/**
 * Helper function for article form alter hooks.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _burdastyle_article_form_alter_helper(&$form, FormStateInterface $form_state) {
  // Move promote fields to options group.
  $form['promote_top_presenter']['#group'] = 'options';
  $form['promote_front_presenter']['#group'] = 'options';
  $form['promote_channel']['#group'] = 'options';
  $form['promote_channel_presenter']['#group'] = 'options';
  $form['sponsored']['#group'] = 'options';

  // Add CSS file for layout optimization.
  $form['#attached']['library'][] = 'burdastyle_article/article_form_styling';
}

/**
 * Implements hook_preprocess_node().
 */
function burdastyle_article_preprocess_node(&$variables) {
  /* @var Node $node */
  $node = &$variables['elements']['#node'];
  if ($node->bundle() == "article") {
    $variables['datetime'] = \Drupal::service('date.formatter')
      ->format($node->created->value, 'html_datetime');
    $variables['timestamp'] = \Drupal::service('date.formatter')
      ->format($node->created->value, 'infinite_timestamp');

    $author = $node->getOwner();
    if ($author->isActive()) {

      // Get absolute URL from node alias URL.
      $author_absolute_url = \Drupal::service('path.alias_manager')
        ->getAliasByPath('/user/' . $author->id());
      $author_absolute_url = Url::fromUri('base:/' . $author_absolute_url, array('absolute' => TRUE));

      // Build author teaser.
      $author_teaser = array(
        '#theme' => 'author_teaser',
        '#elements' => ['#user' => $author,],
        '#author_id' => $node->getOwnerId(),
        '#author_url' => $author_absolute_url->toString(),
        '#author_picture' => user_view($author, 'author_teaser'),
        '#timestamp' => $variables['timestamp'],
        '#datetime' => $variables['datetime'],
      );

    }
    else {

      // Build anonymous author teaser.
      $author_teaser = array(
        '#theme' => 'author_teaser',
        '#elements' => ['#user' => $author,],
        '#author_id' => 0,
        '#timestamp' => $variables['timestamp'],
        '#datetime' => $variables['datetime'],
      );
    }

    $variables['author_teaser'] = render($author_teaser);
  }
}
