<?php

/**
 * Implements hook_theme_suggestions_alter().
 */
function burdastyle_sponsor_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables, $hook) {
  if (!empty($variables['elements']['#view_mode'])) {
    $suggestions[] = $hook . '__' . $variables['elements']['#view_mode'];
  }
}

/**
 * Implements hook_preprocess_node().
 */
function burdastyle_sponsor_preprocess_node(&$variables) {
  /* @var Node $node */
  $node = &$variables['elements']['#node'];

  // Get sponsor type when field exists.
  if ($node->hasField('field_sponsor_type') &&
    !$node->field_sponsor_type->isEmpty()) {

    $variables['sponsor_type'] = $node->field_sponsor_type->value;
  }

  if ($node->hasField('field_campaign') && !$node->field_campaign->isEmpty()) {
    $variables['has_campaign'] = TRUE;
  }

}

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function burdastyle_sponsor_preprocess_taxonomy_term(&$variables) {
  $variables['logo_url'] = theme_get_setting('logo.url');
}
