<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\EntityReferenceFieldItemList;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Adjust entity forms for node and taxonomy_term entities to use Thunder Admin styling.
 */
function burdastyle_thunder_admin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

	/* @var EntityInterface $entity */
	if (method_exists($form_state->getFormObject(), 'getEntity') && $entity = $form_state->getFormObject()->getEntity()) {
		switch ($entity->getEntityTypeId()) {
			case 'node':
			case 'taxonomy_term':
  			_burdastyle_thunder_admin_form_alter_helper($form, $form_state, $form_id);
	  		break;
		}
	}
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function burdastyle_thunder_admin_form_node_ecommerce_slider_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['field_css_styles']['#disabled'] = TRUE;
  $form['field_css_styles']['widget'][0]['value']['#placeholder'] = 'Save this E-Commerce Slider first and edit it again to adjust CSS styling.';

  // TODO: Remove when color fields are removed from ecommerce_slider.
  $form['field_color_box']['#disabled'] = TRUE;
  $form['field_color_button']['#disabled'] = TRUE;
  $form['field_color_contrast']['#disabled'] = TRUE;
  $form['field_title_color']['#disabled'] = TRUE;
  $form['field_arrow_foreground']['#disabled'] = TRUE;
  $form['field_arrow_background']['#disabled'] = TRUE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function burdastyle_thunder_admin_form_node_ecommerce_slider_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Get node object of form.
  $node = $form_state->getFormObject()->getEntity();

  // Replace tokens in placeholder of field_css_styles.
  $token = \Drupal::service('token');
  $cssPlaceholder = burdastyle_thunder_admin_get_ecommerce_slider_css_placeholder();
  $cssPlaceholder = $token->replace($cssPlaceholder, ['node' => $node]);
  $form['field_css_styles']['widget'][0]['value']['#placeholder'] = $cssPlaceholder;
  $form['#attached']['library'][] = 'burdastyle_thunder_admin/ecommerce_slider_form';

  // TODO: Remove when color fields are removed from ecommerce_slider.
  $form['field_color_box']['#disabled'] = TRUE;
  $form['field_color_button']['#disabled'] = TRUE;
  $form['field_color_contrast']['#disabled'] = TRUE;
  $form['field_title_color']['#disabled'] = TRUE;
  $form['field_arrow_foreground']['#disabled'] = TRUE;
  $form['field_arrow_background']['#disabled'] = TRUE;
}

/**
 * Helper function for article form alter hooks.
 *
 * @param $form
 * @param FormStateInterface $form_state
 */
function _burdastyle_thunder_admin_form_alter_helper(&$form, FormStateInterface $form_state, $form_id) {

	// Get the current user.
	$user = \Drupal::currentUser();

	// Move some fields to existing fieldset groups.
	$form['field_hide_created']['#group'] = 'author';
	$form['field_promote_states']['#group'] = 'options';

	// Move ad settings fields into advanced region of form.
	$form['bs_ad_settings'] = [
		'#type' => 'details',
		'#title' => 'Ad settings',
		'#group' => 'advanced',
		'#open' => FALSE,
		'#optional' => TRUE,
		'#access' => $user->hasPermission('view ad settings in forms'),
	];
	$form['field_ad_context']['#group'] = 'bs_ad_settings';
	$form['field_sponsor_type']['#group'] = 'bs_ad_settings';
	$form['field_campaign']['#group'] = 'bs_ad_settings';

	// Move fields for header, sidebar and footer blocks into advanced region of form.
	$form['bs_block_settings'] = [
		'#type' => 'details',
		'#title' => 'Block settings',
		'#group' => 'advanced',
		'#open' => FALSE,
		'#optional' => TRUE,
		'#access' => $user->hasPermission('view block settings in forms'),
	];
	$form['field_header_blocks']['#group'] = 'bs_block_settings';
	$form['field_sidebar_blocks']['#group'] = 'bs_block_settings';
	$form['field_footer_blocks']['#group'] = 'bs_block_settings';

	// Move fields for header media and title into advanced region of form.
	$form['bs_header_settings'] = [
		'#type' => 'details',
		'#title' => 'Header settings',
		'#group' => 'advanced',
		'#open' => FALSE,
		'#optional' => TRUE,
		'#access' => $user->hasPermission('view header settings in forms'),
	];
	$form['field_header_media']['#group'] = 'bs_header_settings';
	$form['field_header_title']['#group'] = 'bs_header_settings';

	// Move fields all extra fields into advanced region of form.
	$form['bs_extra_settings'] = [
		'#type' => 'details',
		'#title' => 'Extra settings',
		'#group' => 'advanced',
		'#open' => FALSE,
		'#optional' => TRUE,
		'#access' => $user->hasPermission('view extra settings in forms'),
	];
	$form['field_promotion_teaser_disable']['#group'] = 'bs_extra_settings';
	$form['field_adsense_active']['#group'] = 'bs_extra_settings';
	$form['field_hide_title']['#group'] = 'bs_extra_settings';
	$form['field_rewe_button']['#group'] = 'bs_extra_settings';

  // Move fields for TVI into advanced region of form.
  $form['bs_tvi_settings'] = [
    '#type' => 'details',
    '#title' => 'TVI settings',
    '#group' => 'advanced',
    '#open' => FALSE,
    '#optional' => TRUE,
    '#access' => $user->hasPermission('administer taxonomy views integrator'),
  ];
  $form['tvi']['#group'] = 'bs_tvi_settings';

	// Add access check for IVW settings.
	$form['field_ivw']['#access'] = $user->hasPermission('view ivw settings in forms');

  // Add BurdaStyle specific CSS for thunder_admin backend theme.
  $form['#attached']['library'][] = 'burdastyle_thunder_admin/form_styling';

  // Add BurdaStyle specific JS for thunder_admin backend theme.
  $form['#attached']['library'][] = 'burdastyle_thunder_admin/edit_plus';

  // Add CSS to fix broken travis tests with position fixed 'content-form-actions' region.
	if (getenv('AH_SITE_ENVIRONMENT') == 'travis') {
		$form['#attached']['library'][] = 'burdastyle_thunder_admin/travis_fix';
	}
  // TODO: check, if still relevant
  // Remove 'save and view amp page' buttons
  unset($form['actions']['save_view_amp']);
  unset($form['actions']['save_view_amp_with_warn']);
}

/**
 * Implements hook_field_widget_WIDGET_ID_form_alter().
 *
 * Required for non-thunder media image fields.
 *
 * @see thunder_media_field_widget_entity_browser_entity_reference_form_alter
 */
function burdastyle_thunder_admin_field_widget_entity_browser_entity_reference_form_alter(&$element, FormStateInterface $form_state, $context) {
	/* @var EntityReferenceFieldItemList $items */
	$items = $context['items'];
	$field_name = $items->getName();
	switch ($field_name) {
		case 'field_header_media':
		case 'field_logo_media':
		case 'field_presenter_media':
			_thunder_media_media_field_widget_form_alter_helper($element, 'image');
			break;
	}
}

/**
 * Implements hook_field_widget_WIDGET_ID_form_alter().
 *
 * Required for viewsreferences, so the default view and display are used.
 *
 */
function burdastyle_thunder_admin_field_widget_viewsreference_autocomplete_form_alter (&$element, FormStateInterface $form_state, $context) {
  $route = \Drupal::service('router.route_provider')
         ->getRouteByName();
  $is_admin = \Drupal::service('router.admin_context')
            ->isAdminRoute($route);
  // we don't want to do this on widget configuration pages.
  if (!$is_admin) {
    $element['target_id']['#access'] = FALSE;
    $element['display_id']['#access'] = FALSE;
    $element['options']['#open'] = TRUE;
  }
}

/**
 * Helper function to get eCommerce Slider CSS placeholder from default theme,
 * base theme or fallback.
 *
 * @return bool|string
 */
function burdastyle_thunder_admin_get_ecommerce_slider_css_placeholder() {
  // Get path to default theme.
  $theme = $config = \Drupal::config('system.theme')->get('default');
  $themePath = drupal_get_path('theme', $theme);

  // Get fallback of CSS placeholder from base theme.
  $cssPlaceholderFile = DRUPAL_ROOT . '/' . $themePath . '/css/ecommerce_slider.tcss';
  if (!file_exists($cssPlaceholderFile)) {
    $themePath = drupal_get_path('theme', 'infinite');
    $cssPlaceholderFile = DRUPAL_ROOT . '/' . $themePath . '/css/ecommerce_slider.tcss';
  }

  // Get eCommerce Slider placeholder for field_css_styles from CSS placeholder file.
  $cssPlaceholder = file_get_contents($cssPlaceholderFile);
  if (!$cssPlaceholder) {
    $cssPlaceholder = <<<EOT
.ecommerce-slider.ecommerce-slider-[node:nid]
.ecommerce-slider__title {
    color: RGBA(255,255,255,1);
}
.ecommerce-slider.ecommerce-slider-[node:nid]
.ecommerce-slider__content {
    background-color: RGBA(34,34,34,1);
}
.ecommerce-slider.ecommerce-slider-[node:nid]
.caption .text-shop {
    color: RGBA(255,255,255,1);
    background-color: RGBA(34,34,34,1);
}
.ecommerce-slider.ecommerce-slider-[node:nid]
.caption .text-shop:hover {
    color: white;
    background-color: #444;
    border-color: #444;
}
.ecommerce-slider.ecommerce-slider-[node:nid]
.swiper-button {
    color: RGBA(255,255,255,1);
    background-color: RGBA(34,34,34,1);
}
.ecommerce-slider.ecommerce-slider-[node:nid]
.swiper-button:hover {
    color: white;
    background-color: #444;
}
EOT;
  }

  return $cssPlaceholder;
}
